package com.toy.robot.rest.exception;

import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.Response.Status;
import javax.ws.rs.ext.ExceptionMapper;
import javax.ws.rs.ext.Provider;

import com.toy.robot.exception.CustomException;

/**
 * This class is a custom exception handler used to send 400 status if any custom 
 * exception is generated by the application.
 *
 */

@Provider
public class CustomExceptionHandler implements ExceptionMapper<CustomException>
{
    /*
     * This method sets the 404 status and exception message in the Response object.
     * 
     * @Param exception   CustomException Object
     * @Return Response   Response Object 
     */
	public Response toResponse(CustomException exception)
    {
        return Response.status(Status.BAD_REQUEST).entity(exception.getMessage()).type(MediaType.APPLICATION_JSON).build(); 
    }
}
