package com.toy.robot.exception;

import java.io.Serializable;

/**
 * This class is used to handle custom exceptions generated by the application.
 */

public class CustomException extends Exception implements Serializable
{
    private static final long serialVersionUID = 1L;
    
    /*
     * Default constructor for exception class
     */
    public CustomException() {
        super();
    }
    
    /*
     * One argument constructor for exception class
     * 
     * @Param msg   custom message set in the exception
     */
    public CustomException(String msg)   {
        super(msg);
    }
    
    /*
     * Two argument constructor for exception class
     * 
     * @Param msg   custom message set in the exception
     * @Param e   Exception generated by application
     */
    public CustomException(String msg, Exception e)  {
        super(msg, e);
    }
}
